### ISSUE TITLE
[Feat]: Add a method to check if type implements a trait

### ISSUE THREAD

**Issue by Veetaha** [rust-marker/marker#305] opened 2023-10-26 16:20 UTC
### Summary

I'd like to implement a lint that checks for unnecessary method calls, when the original value already implements the required trait.
For example useless `.into_iter()` calls where the function already accepts `impl IntoIterator`.

**Comment by xFrednet** [comment] 2023-10-28 14:51
I believe this is a duplicate of https://github.com/rust-marker/marker/issues/141

Either way, definitely something I want to have soon for Marker.

**Comment by xFrednet** [comment] 2023-10-28 14:52
I'll close this issue, in favor of #141

**Closed by xFrednet** 2023-10-28 14:52 UTC
Labels: S-duplicate, C-enhancement
